### ISSUE TITLE
While running jar prints ,wso2carbon.pid file is Not Found

### ISSUE THREAD

**Issue by ruwanta** [Thumimku/DiagnosticsTool#1]
I get following lines printed when i run the jar in target folder.
Please provide documentation on what to configure.

...............loading  OnBoard Diagnostics Tool .............

.............Loading Log File path Configuration data...........

wso2carbon.pid file is Not Found.Please Check the Access Permission and pidpath in wso2conf.xml

**Comment by Thumimku** [comment]
The error caused because the tool can not find the path to wso2carbon.pid file, because it is not exist in the configured path. Please configure the log file path and pid file path in `LogFileConfiguration`section in `DiagnosticConfig.json` file

**Comment by Thumimku** [comment]
Configure the DiagnosticConfig.json file with the help of "How to Configure JSON file". Close the issue after adding into doc.
